export const SET_USER_DEVICES = 'SET_USER_DEVICES';
export const SET_USER_DATA_LOADING = 'SET_USER_DATA_LOADING';
export const SET_TRANSACTION_STATUS = 'SET_TRANSACTION_STATUS';
export const SET_TRANSACTION_ERROR = 'SET_TRANSACTION_ERROR';
