export const SET_SESSION_LOADING = 'SET_SESSION_LOADING';
export const SET_SESSION_STATUS = 'SET_SESSION_STATUS';
export const SET_SESSION_TOKEN = 'SET_SESSION_TOKEN';
export const SET_SESSION_EXPIRY = 'SET_SESSION_EXPIRY';
export const ADD_SESSION_USER_ID = 'ADD_SESSION_USER_ID';
export const ADD_SESSION_USER_NAME = 'ADD_SESSION_USER_NAME';
export const ADD_SESSION_LOGIN_ERROR = 'ADD_SESSION_LOGIN_ERROR';
export const ADD_SESSION_WARNING = 'ADD_SESSION_WARNING';
