export const SET_SESSION_LOADING = 'SET_SESSION_LOADING';
export const SET_SESSION_STATUS = 'SET_SESSION_STATUS';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_SESSION_EXPIRY = 'SET_SESSION_EXPIRY';
export const ADD_SESSION_ID = 'ADD_SESSION_ID';
export const ADD_SESSION_LOGIN_ERROR = 'ADD_SESSION_LOGIN_ERROR';
export const ADD_SESSION_WARNING = 'ADD_SESSION_WARNING';
